### ISSUE TITLE
Section Sequence Number button on Donor page should be optional

### ISSUE THREAD

**Issue by yding98** [mother-db/ezEMLmotherDB#10]
Section Sequence Number is optional in XSD, but it is required on the Donor page. 

<img width="245" alt="Screen Shot 2022-11-02 at 16 12 31" src="https://user-images.githubusercontent.com/105881836/199619704-1d80a559-24f8-47fe-abfa-159c3fa153eb.png">

**Comment by wlbaird25** [comment]
Removed required field for SectionSeqNum. Changes have been committed and merged with Dev
