### ISSUE TITLE
Keywords - hide LTER Vocabulary 

### ISSUE THREAD

**Issue by dietrichasuedu** [mother-db/ezEMLmotherDB#14]
Can you hide the LTER Vocabulary drop-down box? We would like the box hidden in case we want to change that vocabulary with one for MOTHER. 

The comment on that page also needs to be revised to just say enter a keyword.

**Comment by wlbaird25** [comment]
LTER vocabulary drop-down has been hidden within the webapp/views/resources/templates/keyword.html

An HTML span tag was added to make the text field full width, and the original code was commented out and left directly below the new span tag.
