### ISSUE TITLE
Donor Page Specimen Tissue default to ovary

### ISSUE THREAD

**Issue by dietrichasuedu** [mother-db/ezEMLmotherDB#17]
Please have the donor "specimen tissue" field autofill with ovary. It is the only allowed value at this point. 

For the custom validator for the Donor page, this field to be verified as ovary .

**Comment by wlbaird25** [comment]
This field is already set as a default value of "ovary". I will verify the code on the development branch (which is on the dev VM currently) is accurate to this default value.

**Comment by wlbaird25** [comment]
I have checked and verified the form data on the development branch, and my branch, and it does have a default value of "ovary" already. Let me know if there is an issue with this populating in a particular situation or environment. I have tested this default value with  a new document, and it does work on my end, closing the issue.
