### ISSUE TITLE
Image name and the file uploaded do not display as entries after "Upload and continue" button clicked

### ISSUE THREAD

**Issue by KarenWatanabe** [mother-db/ezEMLmotherDB#18]
After an image filename is entered and an image uploaded, these should be displayed to the user when the user navigates back to the Image page, or if the document is closed and reopened.  Currently, when either of these actions are performed, the Name field is blank, and the file uploaded doesn't appear.

**Comment by jpraymer** [comment]
Images should now be stored per project, and retained between sessions. The file name of the current upload is now also displayed in the Image form.
