### ISSUE TITLE
Immunohistochemistry (IHC) page should only appear if we have an IHC slide

### ISSUE THREAD

**Issue by KarenWatanabe** [mother-db/ezEMLmotherDB#19]
The Immunohistochemistry (IHC) page appears after clicking "Save and Continue" on the Donor page.  The required entires on this page do not allow the user to "Save and Continue" without completing the form.  This page is only needed if we have an IHC slide, so a couple of possible solutions include:

1.  At the top of the page (below "Immunohistochemistry") or in the tool tip, state that if the slide is not an IHC slide,  use the navigation menu on the left to go to "Submit Metadata" or any other part of the metadata.
2. Have this page only appear if IHC is selected from one of the dropdown lists on the Donor page.  We need to ask Dr. Zelinski where IHC should be listed in one of the dropdown lists, or if should be a box that gets checked.

**Comment by jpraymer** [comment]
Added a field that determines if IHC info is to be filled in on the IHC page.
