### ISSUE TITLE
Donor Page Gender default to female

### ISSUE THREAD

**Issue by yding98** [mother-db/ezEMLmotherDB#20]
Please have the donor 'Gender' field autofill with female. It is the only allowed value in XSD. 

<img width="447" alt="Screen Shot 2022-12-05 at 22 58 03" src="https://user-images.githubusercontent.com/105881836/205831072-11e8ce20-0cb6-42a6-9e4a-db9cde1557de.png">

**Comment by jpraymer** [comment]
Autofill has been set to female with added validation.
