### ISSUE TITLE
Donor Page 'donorYear', 'donorDay' and 'Day of Cycle' should be nillable

### ISSUE THREAD

**Issue by yding98** [mother-db/ezEMLmotherDB#21]
When I leave donorYear, donorDay, and Day of Cycle empty, they should have xsi:nil = 'true'. 

<xsd:element name="donorYears" type="xsd:nonNegativeInteger" />
<xsd:element name="donorDays" type="xsd:nonNegativeInteger" nillable="true"/>

        <xsd:complexType name="donorAgeType">
		<xsd:sequence>
			<xsd:element ref="donorYears" minOccurs="0" />
			<xsd:element ref="donorDays" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

<xsd:element name="dayOfCycle" type="xsd:nonNegativeInteger" nillable="true" />

**Comment by srande** [comment]
donorYear, donorDay, and dayOfCycle now get set to nil when empty.
donorAge and specimenCycle are set to nil when all child elements are empty.
