### ISSUE TITLE
login screen needs to be updated to take off Google, Github, Orcid

### ISSUE THREAD

**Issue by dietrichasuedu** [mother-db/ezEMLmotherDB#3]

**Comment by wlbaird25** [comment]
Updated Log In page on  WilliamDev, will be pushing to Development and then to Dev VM.

**Comment by wlbaird25** [comment]
Removed Google, Github, and ORCID login options from initial loading page, and simply has "Log In" now. These changes have been merged with Development branch and synchronized with the dev machine.
