### ISSUE TITLE
Image Page 'Additional Info' needs correct

### ISSUE THREAD

**Issue by yding98** [mother-db/ezEMLmotherDB#40]
The following is what I found about 'Additional Info' element in EML xsd, it might be the wrong element, please verify it. 

<xs:element name="additionalInfo" type="txt:TextType" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:appinfo>
            <doc:tooltip>Additional Information</doc:tooltip>
            <doc:summary>Any extra information pertitent to the
            resource.</doc:summary>
            <doc:description>This field provides any information that is not
            characterized by the other resource metadata
            fields.</doc:description>
            <doc:example>Copyright 2001, Robert Warner</doc:example>
          </xs:appinfo>
        </xs:annotation>
      </xs:element>

But it generates an error in both cases:

when Additional info is empty, the error message is as follows:
 EML - ../Whelk/%23%23%23_UN_001x.xml:119:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'additionalInfo': This element is not expected.

when it is filled out, the error message is as follows:
 EML - ../../Downloads/Busycotypus%20canaliculatus%20reproductive%20data,%20Vineyard%20Sound,%202020/97_UN_003c.ome.xml:152:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'additionalInfo': This element is not expected.

**Comment by jpraymer** [comment]
This was most likely caused by the additional info node not being placed in the correct order relative to other nodes, so hopefully changing the order to match the EML documentation fixed this.
