### ISSUE TITLE
packageId missing in opening eml element when no title specified

### ISSUE THREAD

**Issue by dietrichasuedu** [mother-db/ezEMLmotherDB#42]
When there was no title I get: 

XML specific tests: Failed
The following errors were found:

cvc-complex-type.4: Attribute 'packageId' must appear on element 'eml:eml'.

When I added a title, I get the following error message: 
EML Parser
EML specific tests: Passed.
The tests which are specific to EML, including validation that IDs are present and properly referenced, have passed.

XML specific tests: Failed
The following errors were found:

cvc-complex-type.2.4.a: Invalid content was found starting with element 'otherEntity'. One of '{title, creator}' is expected.

**Comment by jpraymer** [comment]
This sounds like things are working as intended, as we discussed that the packageId should be derived from the title with no way to input a packageId separately.

**Comment by jpraymer** [comment]
Now that I have looked closer it appears that the EML validation page checks for both a Title and Creator simultaneously, as this check is only bypassed once both are present in the document at once. Just having a Title and not a Creator should thus bring up this error. After this requirement is fulfilled, it can be seen that a far larger variety of other nodes are then checked at the same time in a similar manner.
