### ISSUE TITLE
taxonomic coverage is required for MOTHER

### ISSUE THREAD

**Issue by dietrichasuedu** [mother-db/ezEMLmotherDB#43]
please validate in "Check Metadata" accordingly - 

Also, update the warning that at least one geographic/temporal/taxonomic is required. 
For MOTHER, taxonomic is required - geographic and temporal are optional 

![image](https://user-images.githubusercontent.com/10838163/220448080-12129c5a-1df2-425b-b409-299f7dc1eaef.png)

**Comment by dietrichasuedu** [comment]
In Check Metadata, is there a way to add a validation rule to verify that genus and species is part of the taxonomic coverage?

**Comment by jpraymer** [comment]
Taxonomic Coverage is now the only coverage item marked as required. Presence of Genus and Species is also checked for the whole document.
