### ISSUE TITLE
Folder is the document name - NOT the title

### ISSUE THREAD

**Issue by dietrichasuedu** [mother-db/ezEMLmotherDB#44]
The title is the packageId

**Comment by jpraymer** [comment]
Downloaded folder will now use the document name.

**Comment by dietrichasuedu** [comment]
This is now broken again? 
Folder name should be the active document name 
Files should be: 
imagename.ext
imagename.xml

Currently, an imagename.ome.tif has an xml file named iamgename.ome.xml

**Comment by jpraymer** [comment]
Multiple file extensions within the same file name are now taken into account for uploaded files.
