### ISSUE TITLE
Image Additional Info Tooltip needs to be added 

### ISSUE THREAD

**Issue by dietrichasuedu** [mother-db/ezEMLmotherDB#45]
Suggest key:value pairs to aid parsing later

**Comment by jpraymer** [comment]
An additional tooltip has been added next to the Additional Info form. For now it reads the following:

"Although not required, it is suggested to add key:value pairs for measurement data to aid parsing."

This tooltip can be modified in the Google Drive folder's "help" file under "other_entity_info".
