### ISSUE TITLE
About link at top of page needs to be updated for MOTHER

### ISSUE THREAD

**Issue by dietrichasuedu** [mother-db/ezEMLmotherDB#5]

**Comment by wlbaird25** [comment]
about.html file is located in  webapp/home/templates/about.html

**Comment by dietrichasuedu** [comment]
Here is a first draft of the About for ezEML+MOTHER. Please update the existing "About ezEML" but do not Close this issue yet because the leadership team needs to agree on its content before it can be closed. 

About ezEML+MOTHER
 
ezEML+MOTHER is a form-based online application designed to streamline the creation of metadata in the Ecological Metadata Language (EML) with additional metadata for MOTHER (Multispecies Ovarian Tissue Histology Electronic Repository). Metadata is data that describes a data source and is a crucial component of the FAIR Guiding Principles for scientific data management and stewardship. For MOTHER, a data source is a histology slide of an ovary. EML essentially documents the provenance of the data (e.g., contact, intellectual rights, funding sources, etc.) and the inclusion of the MOTHER additional metadata documents information pertaining to the ovarian histology slide and its donor animal. 

ezEML+MOTHER leveraged the existing ezEML tool (https://ezeml.edirepository.org/eml/), which was created by the Environmental Data Initiative (EDI). In Fall 2021, the ezEML github project was forked and customized for the MOTHER project. The tool assists users in the creation of an EML+MOTHER document, which is saved in an XML (eXtensible Markup Language) file that must adhere to the EML and MOTHER structural specifications.

For MOTHER, where a donor animal may have multiple histology slides, a user can upload an existing EML+MOTHER XML document and then change the specifics related only to the new slide being described. 

Your feedback is welcome (email).

**Comment by wlbaird25** [comment]
Updated williamDev branch with the above about info for now. Keeping this issue open until final draft is ready to be implemented.
