### ISSUE TITLE
donorAge and specimenCycle are including nested elements when nilled

### ISSUE THREAD

**Issue by mlbarden** [mother-db/ezEMLmotherDB#51]
When donorYears, donorDays, and specimenCycle are left blank in ezEML+MOTHER, the resulting XML file still includes the nested elements. See lines 166-168 and lines 177-179 in the attached file.
[nillabletest.txt](https://github.com/mother-db/ezEMLmotherDB/files/10985136/nillabletest.txt)

**Comment by srande** [comment]
Nested elements are now removed when left blank.
