### ISSUE TITLE
Error accessing ezEML+MOTHER with my account

### ISSUE THREAD

**Issue by yding98** [mother-db/ezEMLmotherDB#53]
I have been having some trouble accessing the ezEML+MOTHER after I tried to upload an invalid XML file. I tried using two different browsers, but I keep running into an error that blocks my access to ezEML+MOTHER. I attached the screenshot of the error message below. 

My username is yding98@asu.edu. Please help me to fix this issue. I would really appreciate it. 

<img width="1682" alt="Screen Shot 2023-03-15 at 18 56 56" src="https://user-images.githubusercontent.com/105881836/225489889-8f80fa53-b6cf-4607-b96c-fd21dba59090.png">

**Comment by jpraymer** [comment]
Implemented a fix for this specific issue regarding missing <para> node contents. You should now be able to log in normally.
