### ISSUE TITLE
User Guide at top of page needs to be updated for MOTHER

### ISSUE THREAD

**Issue by dietrichasuedu** [mother-db/ezEMLmotherDB#6]

**Comment by wlbaird25** [comment]
User Guide links commented out and committed on WilliamDev. Being merged with Development next, then cloned to Dev VM.

**Comment by wlbaird25** [comment]
User guide links have been commented out and "To Be Supplied" has been added in its place. These changes have been committed and merged with Development branch. These changes have been synchronized with the VM dev machine.
