### ISSUE TITLE
Error message on the Donor Page

### ISSUE THREAD

**Issue by yding98** [mother-db/ezEMLmotherDB#62]
When I created a new document and filled out the Donor page, the 'Check Metadata' page displayed an error pertaining to the 'Donor Stage of Cycle' when selected. The error message showed below. 
<img width="1153" alt="Screen Shot 2023-03-26 at 18 22 59" src="https://user-images.githubusercontent.com/105881836/227819114-b4e8b279-84ee-40d9-992e-0c6fb6ec5452.png">

<img width="1286" alt="Screen Shot 2023-03-26 at 18 21 49" src="https://user-images.githubusercontent.com/105881836/227819010-ef07b74d-4466-49f6-9859-73ac470df5b7.png">

**Comment by jpraymer** [comment]
The Donor Stage Of Cycle check in "Check Metadata" has now been fixed by making sure the element is optional. This check will now only occur if an incorrect element is present in the corresponding node if it exists.

**Comment by jpraymer** [comment]
Magnification node error has been fixed.
