### ISSUE TITLE
Warning message was presented, despite selecting the CC BY option

### ISSUE THREAD

**Issue by yding98** [mother-db/ezEMLmotherDB#63]
On the 'Check Metadata' page, despite selecting the CC BY option, a warning for the Intellectual Rights page was presented. 
<img width="950" alt="Screen Shot 2023-03-26 at 18 26 12" src="https://user-images.githubusercontent.com/105881836/227819434-7d01d8c4-c495-490e-ada7-ef67e2dcf9cd.png">

**Comment by jpraymer** [comment]
Fixed by updating the validator to account for <para> tags.
