### ISSUE TITLE
? items for ezEML+MOTHER needs to be reviewed and updated

### ISSUE THREAD

**Issue by dietrichasuedu** [mother-db/ezEMLmotherDB#7]

**Comment by wlbaird25** [comment]
I was able to add a donor help text and add the donor help button content to the donor page successfully. I will continue editing the "?" button fields for the donor and IHC pages, as well as any subsequent pages that need editing.

**Comment by wlbaird25** [comment]
? button content/text has been updated for the Immunohistochemistry page. A new section in help.txt has been added for the specified help button.

**Comment by dietrichasuedu** [comment]
Completed July 2023
