### ISSUE TITLE
Donor page to update "Stage of Cycle" combo box based on a new combo box for scientists to choose

### ISSUE THREAD

**Issue by dietrichasuedu** [mother-db/ezEMLmotherDB#8]

**Comment by dietrichasuedu** [comment]
For example, right now the xsd has menstrual and estrous stage types. 
This probably will mean that the follicular and luteal drop-downs will go on a new line.

**Comment by jpraymer** [comment]
Added a selection for "Menstrual" and "Estrous" stage types to the form.
