### ISSUE TITLE
Accessing issues with ezEML+MOTHER

### ISSUE THREAD

**Issue by yding98** [mother-db/ezEMLmotherDB#82]
I tried Google Chrome and Safari to access ezEML+MOTHER, but both of them showed 'This site can't be reached'. I attached screenshots below. 
<img width="649" alt="Screen Shot 2023-04-15 at 13 09 33" src="https://user-images.githubusercontent.com/105881836/232251211-f3cc0ac4-3cf9-49f1-85f0-1e372dc7af3b.png">
<img width="708" alt="Screen Shot 2023-04-15 at 13 09 53" src="https://user-images.githubusercontent.com/105881836/232251221-9cfa5d28-8a50-4fce-9fae-4112c055d615.png">

**Comment by jpraymer** [comment]
The website was down at the time and has since been reinstated.
