### ISSUE TITLE
Accessing errors of my account 

### ISSUE THREAD

**Issue by yding98** [mother-db/ezEMLmotherDB#89]
When I tried to delete the unnecessary documents on ezEML+MOTHER, I encountered an error that prevented me from accessing the system. Please help me in resolving this issue as I need to create additional XML files for our collaborators.
<img width="1201" alt="Screen Shot 2023-05-02 at 17 17 50" src="https://user-images.githubusercontent.com/105881836/235811618-55ed2af8-9fa9-4a1f-beee-8565dbbb1170.png">

**Comment by yding98** [comment]
my account is yding98@asu.edu

**Comment by jpraymer** [comment]
Fixed by requiring a filename attribute to be present before running the responsible method.
